<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#ndarray-creation" data-toc-modified-id="ndarray-creation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>ndarray creation</a></span><ul class="toc-item"><li><span><a href="#Sampling" data-toc-modified-id="Sampling-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sampling</a></span></li></ul></li><li><span><a href="#reshape" data-toc-modified-id="reshape-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#transformation" data-toc-modified-id="transformation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>transformation</a></span><ul class="toc-item"><li><span><a href="#element-wise" data-toc-modified-id="element-wise-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>element-wise</a></span></li><li><span><a href="#shape-changing" data-toc-modified-id="shape-changing-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>shape-changing</a></span><ul class="toc-item"><li><span><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Matrix multiplication</a></span></li><li><span><a href="#Vector-length" data-toc-modified-id="Vector-length-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Vector length</a></span></li></ul></li></ul></li><li><span><a href="#Deep-Learning" data-toc-modified-id="Deep-Learning-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Deep Learning</a></span><ul class="toc-item"><li><span><a href="#log-loss-/-cross-entropy" data-toc-modified-id="log-loss-/-cross-entropy-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>log loss / cross-entropy</a></span></li><li><span><a href="#Weight-Initialization" data-toc-modified-id="Weight-Initialization-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Weight Initialization</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np
np.set_printoptions(suppress=True)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"  # print all cell outputs and not just the last one

## ndarray creation

In [2]:
np.array([1,2,3])
np.array([[1, 2], [3, 4]]) # shape (2,2)

# create evenly spaced on log space
alphas = np.logspace(0, -4, num=5, base=10.)

np.arange(1, 4) # [1 2 3]
x = np.arange(1, 10, dtype=np.float64).reshape(3,3)

np.random.permutation(x)

np.zeros((3, 1)) # dtype('float64')
np.zeros_like(x) # same shape as x

ones = np.ones((32, 1), dtype=np.int16)

array([1, 2, 3])

array([[1, 2],
       [3, 4]])

array([1, 2, 3])

array([[4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.]])

array([[0.],
       [0.],
       [0.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Sampling

In [3]:
# create array of shape 32x32x3 with random samples from uniform distribution over [0, 1)
img = np.random.rand(32, 32, 3)

# sample array of shape 5x1 from standard normal distribution (mean 0 & variance 1)
np.random.randn(5, 1)

y = np.random.randint(1, 5, (3,1))

# sample without replacement
# can be used to create indices to randomly divide dataset
np.random.permutation(10)

array([[ 0.23304352],
       [-0.10562951],
       [ 2.12127309],
       [-0.50379179],
       [-0.49687924]])

array([6, 9, 0, 8, 5, 1, 3, 4, 7, 2])

## reshape

In [4]:
# create 1-column vector from array
img_flat = img.reshape(np.prod(img.shape), 1)
img_flat.shape

# alternative way 
# np docs : "One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions."
img_flat2 = img.reshape(-1, 1)

np.unique(img_flat == img_flat2, return_counts=True)

(3072, 1)

(array([ True]), array([3072]))

## transformation

### element-wise

In [5]:
# most functionality is available as ndarray method and np function
np.round(x, 2) # x.round(2) 

# element-wise multiplication
x * 2 # np.multiply(x, 2)

# all 3 approaches calculate square element-wise
# np.power(x, 2)
# np.square(x)
x**2 

# misc methods
np.exp(x)
# np.tanh(x)
# np.log(x)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [  54.59815003,  148.4131591 ,  403.42879349],
       [1096.63315843, 2980.95798704, 8103.08392758]])

In [6]:
# probabilistic classification
y_prob = np.random.rand(10, 1)
y_pred = (y_prob > 0.5)
np.mean(y_pred) # numpy can convert boolean to 1/0

0.8

### shape-changing

In [7]:
np.sum(x)

x.T # transpose

45.0

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

#### Dot product

In [8]:
np.dot(x, y)

array([[16.],
       [40.],
       [64.]])

#### Matrix multiplication

In [9]:
np.matmul(x, y)
# Python 3.5 adds magic function __matmul__ which can be called with '@'
x @ y

array([[16.],
       [40.],
       [64.]])

array([[16.],
       [40.],
       [64.]])

#### Vector length

In [10]:
x = np.arange(1,4) # [1 2 3]
np.linalg.norm(x) # length of the vector: sqrt(1**2 + 2**2 + 3**3) == sqrt(14) == 3.74...

3.7416573867739413

## Deep Learning

### log loss / cross-entropy 

In [11]:
Y = np.array([1, 0, 1, 1, 0])
Y_pred = np.array([0.8, 0.1, 0.9, 0.6, 0.05])
m = Y.shape[0]

# option 1: using matrix multiplication
cost = -1/m * (np.dot(Y.T, np.log(Y_pred)) + np.dot(1-Y.T, np.log(1-Y_pred)))

# option 2: using np.sum + element-wise multiplication
cost2 = -1/m * (np.sum(Y * np.log(Y_pred)) + np.sum((1-Y) * np.log(1-Y_pred)))
cost2

# option 3: scikit-learn :-)
from sklearn.metrics import log_loss
log_loss(Y, Y_pred)

0.19919670015668076

0.19919670015668073

### Weight Initialization

In [12]:
layers_dims = [1024, 512, 512, 256, 1]

l = 1
# Xavier
np.random.randn(layers_dims[l], layers_dims[l-1]) * np.sqrt(1./layers_dims[l-1])
# He et al. 2015
np.random.randn(layers_dims[l], layers_dims[l-1]) * np.sqrt(2./layers_dims[l-1]) 

array([[ 0.02457816,  0.01693632,  0.00994837, ...,  0.02994344,
        -0.04753825,  0.04153849],
       [-0.00557949, -0.01958601,  0.00920372, ...,  0.03111583,
         0.04006163, -0.02953414],
       [-0.03021859,  0.02825443, -0.01128457, ..., -0.02052847,
         0.01613534, -0.00344512],
       ...,
       [-0.01966023,  0.01844714, -0.0341912 , ...,  0.0154537 ,
         0.05115973,  0.04656195],
       [ 0.04438327, -0.01179702,  0.02944869, ..., -0.018531  ,
        -0.01995261, -0.00471176],
       [ 0.01261908, -0.02087508,  0.00144148, ...,  0.01631626,
        -0.00664304,  0.03012115]])

array([[ 0.04403107, -0.02507297,  0.02122098, ..., -0.04696683,
        -0.01127871, -0.01896457],
       [-0.06478163,  0.0051364 , -0.01068406, ...,  0.01271741,
        -0.00202111, -0.02215773],
       [-0.05195645,  0.03597704,  0.03798302, ..., -0.04566305,
        -0.00840224, -0.00349142],
       ...,
       [ 0.06321923,  0.02471191, -0.05249893, ..., -0.02279615,
        -0.00227544,  0.05126108],
       [ 0.01411151,  0.01079825, -0.04587084, ...,  0.04247064,
        -0.06456127,  0.01748129],
       [ 0.06294662, -0.08762309, -0.00252301, ..., -0.00005524,
         0.06966577,  0.00590748]])