<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#ndarray-creation" data-toc-modified-id="ndarray-creation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>ndarray creation</a></span><ul class="toc-item"><li><span><a href="#Sampling" data-toc-modified-id="Sampling-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Sampling</a></span></li></ul></li><li><span><a href="#reshape" data-toc-modified-id="reshape-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#transformation" data-toc-modified-id="transformation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>transformation</a></span><ul class="toc-item"><li><span><a href="#element-wise" data-toc-modified-id="element-wise-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>element-wise</a></span></li><li><span><a href="#shape-changing" data-toc-modified-id="shape-changing-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>shape-changing</a></span><ul class="toc-item"><li><span><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Matrix multiplication</a></span></li><li><span><a href="#Vector-length" data-toc-modified-id="Vector-length-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Vector length</a></span></li></ul></li></ul></li><li><span><a href="#Deep-Learning" data-toc-modified-id="Deep-Learning-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Deep Learning</a></span><ul class="toc-item"><li><span><a href="#log-loss-/-cross-entropy" data-toc-modified-id="log-loss-/-cross-entropy-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>log loss / cross-entropy</a></span></li><li><span><a href="#Weight-Initialization" data-toc-modified-id="Weight-Initialization-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Weight Initialization</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np

## ndarray creation

In [3]:
np.array([1,2,3])
np.array([[1, 2], [3, 4]]) # shape (2,2)

# create evenly spaced on log space
alphas = np.logspace(0, -4, num=5, base=10.)

np.arange(1, 4) # [1 2 3]
x = np.arange(1, 10, dtype=np.float64).reshape(3,3)

np.random.permutation(x)

np.zeros((32, 1)) # a3.dtype -> dtype('float64')
ones = np.ones((32, 1), dtype=np.int16)

### Sampling

In [4]:
# create array of shape 32x32x3 with random samples from uniform distribution over [0, 1)
img = np.random.rand(32, 32, 3)

# sample array of shape 10x1 from standard normal distribution (mean 0 & variance 1)
np.random.randn(10, 1)

# sample without replacement
# can be used to create indices to randomly divide dataset
np.random.permutation(10)

array([4, 6, 9, 7, 8, 1, 5, 3, 2, 0])

## reshape

In [5]:
# create 1-column vector from array
img_flat = img.reshape(np.prod(img.shape), 1)
print(img_flat.shape)

# alternative way 
# np docs : "One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions."
img_flat2 = img.reshape(-1, 1)

np.unique(img_flat == img_flat2, return_counts=True)

(3072, 1)


(array([ True], dtype=bool), array([3072]))

## transformation

### element-wise

In [6]:
# most functionality is available as ndarray method and np function
x.round(2)
np.round(x, 2)

# element-wise multiplication
x * 2
np.multiply(x, 2)

# all 3 approaches calculate square element-wise
np.power(x, 2)
np.square(x)
x**2

# misc methods
np.exp(x)
np.tanh(x)
np.log(x)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947],
       [ 1.94591015,  2.07944154,  2.19722458]])

In [7]:
# probabilistic classification
y_prob = np.random.rand(10, 1)
y_pred = (y_prob > 0.5)
np.mean(y_pred) # numpy can convert boolean to 1/0

0.29999999999999999

### shape-changing

In [8]:
np.sum(x)

45.0

#### Matrix multiplication

In [9]:
np.dot(x, x)
# Python 3.5 adds magic function __matmul__ which can be called with '@'
x @ np.array([2,4,6])

# same as x @ x
np.square(x)

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.],
       [ 49.,  64.,  81.]])

#### Vector length

In [10]:
x = np.arange(1,4) # [1 2 3]
np.linalg.norm(x) # length of the vector: sqrt(1**2 + 2**2 + 3**3) == sqrt(14) == 3.74...

3.7416573867739413

## Deep Learning

### log loss / cross-entropy 

In [15]:
Y = np.array([1, 0, 1, 1, 0])
Y_pred = np.array([0.8, 0.1, 0.9, 0.6, 0.05])
m = Y.shape[0]

# option 1: using matrix multiplication
cost = -1/m * (np.dot(Y.T, np.log(Y_pred)) + np.dot(1-Y.T, np.log(1-Y_pred)))

# option 2: using np.sum + element-wise multiplication
cost2 = -1/m * (np.sum(Y * np.log(Y_pred)) + np.sum((1-Y) * np.log(1-Y_pred)))
print(cost2)

# option 3: scikit-learn :-)
from sklearn.metrics import log_loss
log_loss(Y, Y_pred)

0.199196700157


0.19919670015668073

### Weight Initialization

In [13]:
layers_dims = [1024, 512, 512, 256, 1]

l = 1
# Xavier
np.random.randn(layers_dims[l], layers_dims[l-1]) * np.sqrt(1./layers_dims[l-1])
# He et al. 2015
np.random.randn(layers_dims[l], layers_dims[l-1]) * np.sqrt(2./layers_dims[l-1]) 

array([[-0.04551914, -0.06726978, -0.00925251, ..., -0.02327612,
        -0.03236979, -0.05764494],
       [ 0.06615058,  0.01795833, -0.04263204, ..., -0.08753412,
        -0.0091421 , -0.01714673],
       [ 0.02307681,  0.07745273, -0.08452225, ...,  0.02303265,
        -0.02590978, -0.05230589],
       ..., 
       [-0.01345284,  0.00688317,  0.04233821, ...,  0.03259868,
        -0.03860911,  0.01698858],
       [-0.05219151, -0.09522344,  0.05598307, ...,  0.0146689 ,
        -0.05001574,  0.02077208],
       [-0.00661093, -0.0447327 ,  0.06723794, ..., -0.01664836,
        -0.03083885,  0.02023971]])