<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#ndarray-creation" data-toc-modified-id="ndarray-creation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>ndarray creation</a></span></li><li><span><a href="#reshape" data-toc-modified-id="reshape-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#transformation" data-toc-modified-id="transformation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>transformation</a></span><ul class="toc-item"><li><span><a href="#element-wise" data-toc-modified-id="element-wise-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>element-wise</a></span></li><li><span><a href="#shape-changing" data-toc-modified-id="shape-changing-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>shape-changing</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np

## ndarray creation

In [2]:
np.array([1,2,3])
np.array([[1, 2], [3, 4]]) # shape (2,2)

# create array of shape 32x32x3 with random samples from uniform distribution over [0, 1)
img = np.random.rand(32, 32, 3)

# sample array of shape 10x1 from standard normal distribution (mean 0 & variance 1)
np.random.randn(10, 1)

np.arange(1, 4) # [1 2 3]

np.zeros((32, 1)) # a3.dtype -> dtype('float64')
np.ones((32, 1), dtype=np.int16)

x = np.arange(9, dtype=np.float64).reshape(3,3)

## reshape

In [3]:
# create 1-column vector from array
img_flat = img.reshape(np.prod(img.shape), 1)
print(img_flat.shape)

# alternative way 
# np docs : "One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions."
img_flat2 = img.reshape(-1, 1)

np.unique(img_flat == img_flat2, return_counts=True)

(3072, 1)


(array([ True], dtype=bool), array([3072]))

## transformation

### element-wise

In [4]:
# most functionality is available as ndarray method and np function
x.round(2)
np.round(x, 2)

print(x * 2)
print(x ** 2)

np.exp(x)

[[  0.   2.   4.]
 [  6.   8.  10.]
 [ 12.  14.  16.]]
[[  0.   1.   4.]
 [  9.  16.  25.]
 [ 36.  49.  64.]]


array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

### shape-changing

In [5]:
np.sum(x)

# matrix multiplication
np.dot(x, x)
# Python 3.5 adds magic function __matmul__ which can be called with '@'
x @ np.array([2,4,6])

array([ 16.,  52.,  88.])

In [6]:
x = np.arange(1,4) # [1 2 3]
np.linalg.norm(x) # length of the vector: sqrt(1**2 + 2**2 + 3**3) == sqrt(14) == 3.74...

3.7416573867739413